apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ regexReplaceAll "\\W+" (lower .Chart.Name) "-"}}-web
  labels:
    app: {{ regexReplaceAll "\\W+" (lower .Chart.Name) "-"}}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ regexReplaceAll "\\W+" (lower .Chart.Name) "-"}}-web
  template:
    metadata:
      labels:
        app: {{ regexReplaceAll "\\W+" (lower .Chart.Name) "-"}}-web
    spec:
      containers:
        - name: web
          image: "{{.Values.image.repository }}/{{.Values.image.name}}:{{.Values.image.tag}}"
          livenessProbe:
            httpGet:
              path: /kubernetes/health-check
              port: 3000
          readinessProbe:
            httpGet:
              path: /kubernetes/health-check
              port: 3000
          ports:
          - containerPort: 3000
          env:
          - name: API_URL
            value: http{{ if .Values.ingress.tls }}s{{ end }}://{{.Values.ingress.hostname }}