{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ regexReplaceAll "\\W+" (lower .Chart.Name) "-"}}-web
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png|json)) {        
        add_header Cache-Control "public, max-age=7200";
      }
spec:
  tls:
    - hosts:
        -  {{ .Values.ingress.hostname }}
      secretName: {{ .Values.ingress.hostname }}-tls
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ regexReplaceAll "\\W+" (lower .Chart.Name) "-"}}-web
                port:
                  number: 80
{{- end }}
