apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{lower .Chart.Name}}-web
  labels:
    app: {{lower .Chart.Name}}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{lower .Chart.Name}}-web
  template:
    metadata:
      labels:
        app: {{lower .Chart.Name}}-web
    spec:
      containers:
        - name: web
          image: "{{.Values.image.repository }}/{{.Values.image.name}}:{{.Values.image.tag}}"
          ports:
          - containerPort: 80     
      