apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ regexReplaceAll "\\W+" (lower .Chart.Name) "_"}}-web
  labels:
    app: {{ regexReplaceAll "\\W+" (lower .Chart.Name) "_"}}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ regexReplaceAll "\\W+" (lower .Chart.Name) "_"}}-web
  template:
    metadata:
      labels:
        app: {{ regexReplaceAll "\\W+" (lower .Chart.Name) "_"}}-web
    spec:
      containers:
        - name: web
          image: "{{.Values.image.repository }}/{{.Values.image.name}}:{{.Values.image.tag}}"
          ports:
          - containerPort: 80     
      