apiVersion: v1
kind: Service
metadata:
  name: {{lower .Chart.Name}}-web
spec:
  selector:
    app: {{lower .Chart.Name}}-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
