{{ $host := ternary "zloi.space"
            (print .Values.branch ".zloi.space")
            (or (eq .Values.branch "master") (eq .Values.branch "main")) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ regexReplaceAll "\\W+" (lower .Chart.Name)}}-web
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {        
        add_header Cache-Control "public, max-age=7200";
      }
spec:
  tls:
    - hosts:
        -  {{$host}}
      secretName: "{{$host}}-certificate"
  rules:
    - host: {{$host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ regexReplaceAll "\\W+" (lower .Chart.Name)}}-web
                port:
                  number: 80
